### ISSUE TITLE
On-Demand - Ride cancellation by rider flow implementation issue

### ISSUE THREAD

**Issue by Ganesh11772** [ONDC-Official/automation-framework#188]
### Type of Issue

Question / Clarification

### Summary

1. on_confirm, on_status:- message.order.fulfillments.stops.authorization object is missing in the start section when fulfillments.state is "RIDE_ASSIGNED", "RIDE_ENROTE_PICKUP", "RIDE_ARRIVED_PICKUP". The required fields — "authorization", "status", "valid_to", "type", and "token" — are not being sent by the Seller NP.

2. on_cancel1 & 2 (soft on_cancel, confirm_cancel):- message.order.fulfillments.stops.authorization.type and authorization.token are being sent in both the start and end location objects. Authorization should only be associated with the relevant stop.

3. on_cancel2 (confirm cancel):- message.order.quote.price and message.order.quote.breakup contain incorrect values. 

4. on_cancel2 (confirm cancel):- message.order.fulfillments.state is incorrectly sent as "RIDE_ARRIVED_PICKUP" in the on_cancel2 call.

5. on_cancel2 (confirm cancel):- message.order.cancellation.reason.descriptor.code is incorrectly sent by Seller NP in the confirm cancel (on_cancel2) call. The code value does not match the one shared in the initial cancel call.

6. on_cancel2 (confirm cancel):- SETTLEMENT_AMOUNT value is incorrectly sent by the Seller NP in the on_cancel call.

### Expected Behavior

1. When the fulfillment state is "RIDE_ASSIGNED","RIDE_ENROTE_PICKUP", "RIDE_ARRIVED_PICKUP", the authorization object must be present under message.order.fulfillments.stops.start with all mandatory attributes properly populated.

2. on_cancel1 the authorization details (type and token) must appear only in the start location object & in on_cancel2 authorization details should not be present.

3. Quote.price & breakup should be calculated & sent correctly by seller NP.

4. Fulfillments.state should be "RIDE_CANCELLED" in  on_canecel2 call (confirm cancel call)

5. descriptor.code under message.order.cancellation.reason in on_cancel2 must be identical to the code shared in the cancel call.

6. The SETTLEMENT_AMOUNT should correctly calculated by seller NP.

### Payloads / Logs / Screenshots (if applicable)

[OnDemand_Ride_cancellation_by_rider-OnDemand_Ride_cancellation_by_rider.json](https://github.com/user-attachments/files/23476662/OnDemand_Ride_cancellation_by_rider-OnDemand_Ride_cancellation_by_rider.json)

### Domain

TRV10

### Version

2.1.0

### Reported By (GitHub Handle)

Ganesh11772

**Comment by sourabhsaini11** [comment]
@Ganesh11772, This issue has been resolved on the dev instance. Kindly cross-check and let us know so we can take further action if needed.

**Comment by Ganesh11772** [comment]
@sourabhsaini11 Issue has been tested on Dev environment & below are the findings,
1. on_cancel2 (confirm cancel):- SETTLEMENT_AMOUNT value is incorrectly sent by the Seller NP in the on_cancel call.
2. on_cancel2 (confirm cancel):- message.order.fulfillments.state is incorrectly sent as "RIDE_ARRIVED_PICKUP" in the on_cancel2 call.

**Comment by sourabhsaini11** [comment]
@Ganesh11772, above issues mentioned have been resolved now. Kindly test & let us know

**Comment by Ganesh11772** [comment]
@sourabhsaini11 Issue has been tested on dev & below is the finding,
on_cancel1:- SETTLEMENT_AMOUNT incorrectly sent by buyer NP.

**Comment by sourabhsaini11** [comment]
@Ganesh11772, above mentioned issues are fixed now. Please test & leave your feedback

**Comment by Ganesh11772** [comment]
@sourabhsaini11 Issue has been tested on dev environment & it is not fixed
on_cancel1:- SETTLEMENT_AMOUNT incorrectly sent by buyer NP. SETTLEMENT_AMOUNT should be same as that of the present in the previous call. (SETTLEMENT_AMOUNT calculated as per previous call Quote.price )

**Comment by sourabhsaini11** [comment]
@Ganesh11772, SETTLEMENT_AMOUNT on on_confirm_1 is fixed. value is updated on basis of quote.price

**Comment by Ganesh11772** [comment]
Issue has been tested on dev instance & it is fixed.
