### ISSUE TITLE
[Issue] Transit Insurance | Payload and Flow Issues

### ISSUE THREAD

**Issue by y0geshb** [ONDC-Official/automation-framework#195]
### Type of Issue

Bug Report

### Summary

**search_1**	For all sachet insurance categories, the field category.descriptor.code is sent as MICRO_HOSPICASH_INSURANCE.
**search_2**	The provider ID is hardcoded and sent directly, instead of being taken dynamically from user input or the previous on_search response.
**search_3**	
The UI displays only minimal fields as there is no option to paste or use the payload from the previous response (on_search_2) to populate the next input fields.
Apart from the minimal inputs, other payload values such as provider.items.tags are hardcoded.
There is no option to input provider_id, item_id, or paste the previous response payload manually.
The tag provider.tags.list.code: POLICY_ID (MASTER_POLICY) is hardcoded and does not match the trail.

**select_1**	
Item selection is performed automatically without giving the user an option to choose. In cases with multiple items, the first item is selected by default or appears to be hardcoded.

**on_init**	
The field fulfillments.customer.person.name is incorrectly mapped to the Nominee Name.
The Date of Birth (DOB) is hardcoded (from Swagger).
The contract was updated to exempt the payment URL, but this change was not consumed in the Workbench.
The contact details such as mobile and email were hardcoded instead of maintaining the trail "
**confirm** 	In the Payment.tags, both BAP_TERMS and BPP_TERMS were not sent.
**on_update** 	
The updated_at timestamp is not being updated.
POLICY_DOC: The shared document should have a working URL (not a broken link) so Buyer NPs can test download/display functionality from the UI.

**common issue**	
1. All hardcoded values should be replaced with differentiated dynamic values to enable proper trail checks for NPs (Network Participants).
2. The report generation feature is not working.
3. There is no defined flow or handling for the CD balance error scenario."

### Payloads / Logs / Screenshots (if applicable)

[Purchase_Journey_Transit_Insurance-Purchase_Journey_Transit_Insurance.json](https://github.com/user-attachments/files/23504683/Purchase_Journey_Transit_Insurance-Purchase_Journey_Transit_Insurance.json)
[Discovery_of_Insurer_Providers_and_Master_Policies-null.json](https://github.com/user-attachments/files/23504684/Discovery_of_Insurer_Providers_and_Master_Policies-null.json)
[Discovery_of_Products_from_Master_Policies (Transit Insurance)-null.json](https://github.com/user-attachments/files/23504682/Discovery_of_Products_from_Master_Policies.Transit.Insurance.-null.json)

<img width="606" height="554" alt="Image" src="https://github.com/user-attachments/assets/d8ce02c7-5be5-4c14-a053-d200321c43d2" />

<img width="615" height="251" alt="Image" src="https://github.com/user-attachments/assets/6a92ab03-8f1a-48ce-949a-01820136a50c" />

### Domain

FIS13

### Version

2.0.0

### Testing Mode

All flows

### Scenario Name

All

### Reported By (GitHub Handle)

y0geshb

**Comment by sourabhsaini11** [comment]
@y0geshb, above issues are fixed on dev instance. Kindly check & share feedback if any

**Comment by y0geshb** [comment]
@sourabhsaini11 

Not able to initiate search for Discovery of Insurer Providers and Master Policies

<img width="1829" height="703" alt="Image" src="https://github.com/user-attachments/assets/8537e1a3-571b-45e7-b4f8-dceada906897" /> 

Please let us know how to proceed further

**Comment by y0geshb** [comment]
This issue is not fixed, need discussion 

same as issue 
https://github.com/ONDC-Official/automation-framework/issues/196

**Comment by sourabhsaini11** [comment]
@y0geshb , above issues are fixed on dev instance. Kindly check & share feedback if any

**Comment by y0geshb** [comment]
search_1 For all sachet insurance categories, the field category.descriptor.code is sent as MICRO_HOSPICASH_INSURANCE. -Done
search_2 The provider ID is hardcoded and sent directly, instead of being taken dynamically from user input or the previous on_search response. -Done
search_3
The UI displays only minimal fields as there is no option to paste or use the payload from the previous response (on_search_2) to populate the next input fields. -Done
Apart from the minimal inputs, other payload values such as provider.items.tags are hardcoded.-Done
There is no option to input provider_id, item_id, or paste the previous response payload manually.-Done
The tag provider.tags.list.code: POLICY_ID (MASTER_POLICY) is hardcoded and does not match the trail.-Done

select_1
Item selection is performed automatically without giving the user an option to choose. In cases with multiple items, the first item is selected by default or appears to be hardcoded.-Done

on_init
The field fulfillments.customer.person.name is incorrectly mapped to the Nominee Name.-Done
The Date of Birth (DOB) is hardcoded (from Swagger). -Done
The contract was updated to exempt the payment URL, but this change was not consumed in the Workbench. Done
The contact details such as mobile and email were hardcoded instead of maintaining the trail "-Done
confirm In the Payment.tags, both BAP_TERMS and BPP_TERMS were not sent.-Done
on_update
The updated_at timestamp is not being updated.
POLICY_DOC: The shared document should have a working URL (not a broken link) so Buyer NPs can test download/display functionality from the UI. -Cosmetic will track separately 

common issue

All hardcoded values should be replaced with differentiated dynamic values to enable proper trail checks for NPs (Network Participants). -Not Done (will track seperatly)
The report generation feature is not working. -Not Done (will track seperatly)
There is no defined flow or handling for the CD balance error scenario." -Not Done (will track seperatly)
