### ISSUE TITLE
[Issue] FIS12 | Foreclosure Payload issues

### ISSUE THREAD

**Issue by y0geshb** [ONDC-Official/automation-framework#351]
### Type of Issue

Question / Clarification

### Summary

The Payment object was sent incorrectly. A separate object with the label FORECLOSURE should be present; however, the foreclosure object is currently overriding the previous (first) object in the array.

The quote.price.value is incorrect.

The quote.breakup.PRINCIPAL value was modified in on_update_2, which is not expected.

The loan status is not being updated to COMPLETED after the foreclosure payment is processed.

### Payloads / Logs / Screenshots (if applicable)

[Gold_Loan_Foreclosure_Without_Account_Aggregator-Gold_Loan_Foreclosure_Without_Account_Aggregator.json](https://github.com/user-attachments/files/24260342/Gold_Loan_Foreclosure_Without_Account_Aggregator-Gold_Loan_Foreclosure_Without_Account_Aggregator.json)

### Domain

FIS12

### Version

2.0.2

### Reported By (GitHub Handle)

Yo

**Comment by y0geshb** [comment]
Issues are not resolved, hence reopening the issue

[Gold_Loan_Foreclosure_Without_Account_Aggregator-Gold_Loan_Foreclosure_Without_Account_Aggregator (1).json](https://github.com/user-attachments/files/25020634/Gold_Loan_Foreclosure_Without_Account_Aggregator-Gold_Loan_Foreclosure_Without_Account_Aggregator.1.json)

**Comment by y0geshb** [comment]
As discussed this issue is still not fixed 

[Gold_Loan_Foreclosure_With_Account_Aggregator-Gold_Loan_Foreclosure_With_Account_Aggregator (1).json](https://github.com/user-attachments/files/25238961/Gold_Loan_Foreclosure_With_Account_Aggregator-Gold_Loan_Foreclosure_With_Account_Aggregator.1.json)

**Comment by JyotiSharma0711** [comment]
issues are fixed please test again

**Comment by y0geshb** [comment]
Please find attached the latest retest payload. The same issues are still occurring after assignment, so we can connect to review them.

[Gold_Loan_Foreclosure_Without_Account_Aggregator-Gold_Loan_Foreclosure_Without_Account_Aggregator (2).json](https://github.com/user-attachments/files/25253095/Gold_Loan_Foreclosure_Without_Account_Aggregator-Gold_Loan_Foreclosure_Without_Account_Aggregator.2.json)

**Comment by JyotiSharma0711** [comment]
If there is any issue with the amount, please specify what the correct amount should be.

**Comment by y0geshb** [comment]
fulfillments.state should be COMPLETED instead of COMPLETE

Raised bug for enhancement in swagger too https://github.com/ONDC-Official/automation-framework/issues/770

**Comment by y0geshb** [comment]
The quote.breakup.PRINCIPAL value was modified in on_update_2, which is not expected. - this is still open and will be tracked through #897

[Gold_Loan_Foreclosure_Without_Account_Aggregator-Gold_Loan_With_Account_Aggregator.json](https://github.com/user-attachments/files/25976237/Gold_Loan_Foreclosure_Without_Account_Aggregator-Gold_Loan_With_Account_Aggregator.json)


Rest of the issues are done, hence closing this issue
