### ISSUE TITLE
[Issue] Schema validation is not validating the data/format of the attributes.

### ISSUE THREAD

**Issue by pooja-1102** [ONDC-Official/automation-framework#87]
### Type of Issue

Bug Report

### Summary

Schema validation is not validating the data/format of the attributes 
ex: tried to validate few scenarios of data format specified in the contract but validation tool is not showing any error.
1). incorrect date format used

<img width="1787" height="949" alt="Image" src="https://github.com/user-attachments/assets/0b27cf61-944c-4325-8c60-8121a8ab4f7a" />

2). format issue for duration
<img width="1787" height="949" alt="Image" src="https://github.com/user-attachments/assets/e81412b0-a3bf-4a77-a959-4db69092a3d7" />

3). GPS cordinates not as per contract
<img width="1787" height="949" alt="Image" src="https://github.com/user-attachments/assets/6f51ea7b-f49b-44f6-ba68-c03d2d46bc28" />

### Domain

LOG10

### Version

1.2.5

### Reported By (GitHub Handle)

@pooja-1102

**Comment by vaibhavsharmawits** [comment]
This has been fixed.Please check.

**Comment by pooja-1102** [comment]
@vaibhavsharmawits is it deployed, can you please confirm.
I am still facing this issue

<img width="1775" height="790" alt="Image" src="https://github.com/user-attachments/assets/0ec5eb0a-81dc-468a-8bd1-cb35f52bfa21" />

**Comment by vaibhavsharmawits** [comment]
@pooja-1102 These are fixed and deployed.Please check
